### ISSUE TITLE
file path to slug should be extract to a helper

### ISSUE THREAD

**Issue by FatBoyXPC** [davidjeddy/auto-gourcer#10]
https://github.com/davidjeddy/auto-gourcer/blob/84f5e02f2635fce16d900cb33697a5b426fa60f9/src/Git.php#L78

**Comment by davidjeddy** [comment]
`Slug` in the context of AutoGourcer is the repo's file system directory name. For the sake of preventing confusion with a URL slug any suggestions for a name change?

**Comment by FatBoyXPC** [comment]
I just meant that something like the file path should instead be extracted to a helper function, just to clean up the fact you're concatenating these things everywhere :P

**Comment by davidjeddy** [comment]
Moved to class private property.
