### ISSUE TITLE
any reason to not make this else?

### ISSUE THREAD

**Issue by FatBoyXPC** [davidjeddy/auto-gourcer#11]
https://github.com/davidjeddy/auto-gourcer/blob/84f5e02f2635fce16d900cb33697a5b426fa60f9/src/Git.php#L82

**Comment by davidjeddy** [comment]
Per PHPMD `else` is a messy construct. Recommended to break into if statement to reduce complexity.

**Comment by davidjeddy** [comment]
FIXED, added TODO note.

**Comment by FatBoyXPC** [comment]
Yeah, I agree with that in most cases. however, you're explicitly testing the condition against the inverse of that same condition. That is the most appropriate use case of `else` that exists. I wouldn't want to see `else` if we could use a guard to return early, but in this situation you are doing stuff with that variable afterwards.

A case like this is where I wouldn't want to see `else`:
```
if ($foo) { 
    $bar = 'foo';
} else {
    $bar = 'bar';
}

return $bar;
```

That could instead be
```
if ($foo) {
    return 'foo';
}

return 'bar';
```

**Comment by davidjeddy** [comment]
Fair enough. Refactored method to not need an `else` at all :D.
