### ISSUE TITLE
Probably better to use == here for stuff like empty string

### ISSUE THREAD

**Issue by FatBoyXPC** [davidjeddy/auto-gourcer#12]
https://github.com/davidjeddy/auto-gourcer/blob/84f5e02f2635fce16d900cb33697a5b426fa60f9/src/Git.php#L104

**Comment by davidjeddy** [comment]
In the fn() definition the var is default set to null, in the method if the var is null it triggers a specific action. Thoughts?

**Comment by davidjeddy** [comment]
After looking at this again; type hinting $branch as a string and defaulting to empty. If nothing provided triggers the `get most recent` method call. Else the provided branch name is used.

**Comment by FatBoyXPC** [comment]
Would you want that same action to happen if they passed empty string to the function? That doesn't cover cases such as " " though, so maybe you should trim it? I'm not sure. This is really what sort of behavior you want for your app! I think me, personally, since I know a branch is supposed to be a string, I would `string $branch = ""` and then `if (trim($branch))`

Editing because you ninja'd me: I'm keeping this message just because maybe this thought could still be useful?

**Comment by davidjeddy** [comment]
Using check for empty string and toggling if string is empty. Imma ticket ninja :)
