### ISSUE TITLE
Formatting and extract path to helper

### ISSUE THREAD

**Issue by FatBoyXPC** [davidjeddy/auto-gourcer#17]
https://github.com/davidjeddy/auto-gourcer/blob/84f5e02f2635fce16d900cb33697a5b426fa60f9/src/Git.php#L175

`(string)\file_get_contents` looks like some strange syntax, but `(string) file_get_contents()` looks "normal".

**Comment by davidjeddy** [comment]
(string)\file_get_contents(...) Similar to the \json_*() calls denotes the root SPL namespace. Dont want no other implementation overriding it.
Agreed the loggin system needs work. Slated for 0.4.5 release.

**Comment by FatBoyXPC** [comment]
Well, no other implementation can override it unless you import the function from another namespace in this class, thus, it's all on you :P However, the point I was making was putting a space between `(string)` and the `function()` :P

**Comment by davidjeddy** [comment]
Understood. Adding a space as one appears in method definitions, return param syntax.
FIXED
