### ISSUE TITLE
3rd time I've seen this check, DRY!

### ISSUE THREAD

**Issue by FatBoyXPC** [davidjeddy/auto-gourcer#19]
https://github.com/davidjeddy/auto-gourcer/blob/84f5e02f2635fce16d900cb33697a5b426fa60f9/src/Git.php#L204

**Comment by davidjeddy** [comment]
Agreed. For now BB is the only supported host, before V1.x release I want to support an GiT host that accepts user:pass style HTTP credentials. Slated for completion by 0.5.0 release.
