### ISSUE TITLE
Use spaceship operator here?!

### ISSUE THREAD

**Issue by FatBoyXPC** [davidjeddy/auto-gourcer#23]
https://github.com/davidjeddy/auto-gourcer/blob/84f5e02f2635fce16d900cb33697a5b426fa60f9/src/Git.php#L290

**Comment by davidjeddy** [comment]
Nope. This sorts the array items in reverse order based on the array key. I tried spaceship and the output array was sorted by the original ID :|. I'll leave this as a possible enhancement but atm effort > return.

**Comment by FatBoyXPC** [comment]
Shucks :( I haven't found many use cases of spaceship and was hoping this would work!
