### ISSUE TITLE
Isn't this what basePath is for? Could probably extract this path builder to a helper function

### ISSUE THREAD

**Issue by FatBoyXPC** [davidjeddy/auto-gourcer#6]
https://github.com/davidjeddy/auto-gourcer/blob/84f5e02f2635fce16d900cb33697a5b426fa60f9/src/AutoGourcer.php#L112

**Comment by davidjeddy** [comment]
Logs are kept under /var/log/auto-gourcer, wherein basePath is the path to the application. I considered keeping the logs w/i the app dir tree but as a container service there is no reason not to use the OS log construct.
