### ISSUE TITLE
Refactor getRepoList()

### ISSUE THREAD

**Issue by FatBoyXPC** [davidjeddy/auto-gourcer#9]
https://github.com/davidjeddy/auto-gourcer/blob/84f5e02f2635fce16d900cb33697a5b426fa60f9/src/Git.php#L48

I'm not a real big fan of doing this host checking. In all honesty, I feel like the app should be written in a way that bitbucket is expected to be the only host that works. The future plans may mean to add support, which I feel like should be done with adapters rather than host checking.

At any rate, this method can nicely changed to a short 2 liner!

```
public function getRepoList()
{
    $this->setRepoData($this->host === 'bitbucket.org' ? $this->getRepoListFromBitBucket() : $this->emptyHostResponse());

    return $this;
}
```

However, I think if you had an interface class with methods such as `getRepoList()` then you can get away from all of this useless checking!

**Comment by davidjeddy** [comment]
Road map has including multiple hosts options, GH, GL, BB, etc. ATM this is here as a placeholder until the host logic is abstracted to there own classes. Release road map 0.4.0

**Comment by FatBoyXPC** [comment]
Well if you're only supporting bitbucket for now, then you don't need to check host in the methods. You can just assume it's bitbucket sort of thing. This erases some code and makes it more obvious that only bitbucket is provided. Once you want to add support for GitHub and GitLab, you can make some sort of factory method that will provide the corresponding object that can throw an exception for unsupported hosts!

**Comment by davidjeddy** [comment]
Good point, we can add the checks WHEN we support for other hosts. I can get down with that.
